---
name: cnsga
version: "0.1"
dependencies:
  - xopt
params:
  max_generations: 50
  population_size: 128
  crossover_probability: 0.9
  mutation_probability: 1.0
  selection: auto
  verbose: true
  population: null
