---
name: TNK
description: "Constrainted test function TNK. See Table V in https://www.iitk.ac.in/kangal/Deb_NSGA-II.pdf"
version: "0.1"
dependencies:
  - numpy
params:
variables:
  - x1
  - x2
observations:
  - y1
  - y2
  - c1
  - c2
  - some_array
